### ISSUE TITLE
intel-mkl 2020.0.166-1 no longer has /opt/intel

### ISSUE THREAD

**Issue by stas00** [eddelbuettel/mkl4deb#12]
wrt to your helpful script/instructions - it looks like intel-mkl-2020.0.166-1 and the rest of its .deb packages no longer use `/opt/intel` and instead install everything directly into various standard dirs, which I think makes them visible to compilers w/o needing any env vars.

Moreover the .deb packages no longer include the `mklvars.sh` script, so now we need to figure out how to set all the different env vars manually for all those projects that expect a gazillion of mkl env vars like: `MKL_LIBRARIES MKL_INCLUDE_DIRS MKL_INTERFACE_LIBRARY MKL_SEQUENTIAL_LAYER_LIBRARY MKL_CORE_LIBRARY` and fail w/o those preset.

Probably need to fool those with setting `MKLROOT=/usr`, `MKL_LIBRARIES=/usr/lib/x86_64-linux-gnu`, etc. But I'm not 100% sure what some of those used to point to.

**Comment by stas00** [comment]
Ah, and it now automatically redefines BLAS/LAPACK during the package install:
```
Setting MKL as default BLAS/LAPACK implementation as requested.
update-alternatives: using /usr/lib/x86_64-linux-gnu/libmkl_rt.so to provide /usr/lib/x86_64-linux-gnu/libblas.so (libblas.so-x86_64-linux-gnu) in manual mode
update-alternatives: using /usr/lib/x86_64-linux-gnu/libmkl_rt.so to provide /usr/lib/x86_64-linux-gnu/liblapack.so (liblapack.so-x86_64-linux-gnu) in manual mode
update-alternatives: using /usr/lib/x86_64-linux-gnu/libmkl_rt.so to provide /usr/lib/x86_64-linux-gnu/libblas64.so (libblas64.so-x86_64-linux-gnu) in manual mode
update-alternatives: using /usr/lib/x86_64-linux-gnu/libmkl_rt.so to provide /usr/lib/x86_64-linux-gnu/liblapack64.so (liblapack64.so-x86_64-linux-gnu) in manual mode
```
This is during the run of:
```
sudo apt-get install intel-mkl-full
```

**Comment by eddelbuettel** [comment]
So we no longer need to set up the file `/etc/ld.so.conf.d/mkl.conf` ?  Good.

**Comment by stas00** [comment]
It appears so. It's odd that they made such a major change in the same major version.

**Comment by eddelbuettel** [comment]
So short of a more formal PR (no need really) should I just comment out lines 27 to 30?  Would you be able to test and verify?

**Comment by stas00** [comment]
I was hoping you'd do an install of the latest release at some point in the future and see what needs to be changed. I haven't used the previous setup, so I have no point of reference. I only meant to indicate these changes in this issue.

**Comment by Chem4ai** [comment]
It turns out that the quantum mechanics code GAMESS looks for the mkl libraries in the /opt/intel/ tree, and that is now broken. Intel says that the mkl libraries are installed in /opt/intel/...
While I can see the possible benefit of also having them in the other locations, I think it should not also break what would normally be expected from packages that can use it. Could the transition not keep both with a link from the /opt tree to the standard ones?

**Comment by eddelbuettel** [comment]
You should probably be talking to Intel who produces these .deb files, and/or to the GAMESS people.  This is a simple convenience repo with a helper script that was once useful to me.  It is in no way official or affiliated with Intel.

**Comment by Chem4ai** [comment]
Ah, thank you for the clarification.

Dominic

DRI2, LLC
