### ISSUE TITLE
Repository and package are now named `oneapi-mkl`

### ISSUE THREAD

**Issue by david-cortes** [eddelbuettel/mkl4deb#17]
Newer versions of MKL are now uploaded into a different repository called "oneapi-mkl" instead of just "mkl" - the newest version in the repository referenced in this guide stands at around 2020.something, whereas the current version is 2023.something.

These are the instructions that they provide in their [webpage](https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-download.html?operatingsystem=linux&distributions=aptpackagemanager):
```shell
wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
| gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
sudo apt update
sudo apt install intel-oneapi-mkl
```

**Comment by eddelbuettel** [comment]
See https://github.com/eddelbuettel/mkl4deb#appendix -- this is not really a live repo.
