### ISSUE TITLE
Can the MKL script be adapted for dnf based fedora systems?

### ISSUE THREAD

**Issue by ccaneke** [eddelbuettel/mkl4deb#3]
I'm trying to get __MKL__ installed on my fedora system which uses the dnf package manager. Do you know if __intel MKL__ works for dnf, because I want to use your blog post as a guide line to install it?

**Comment by eddelbuettel** [comment]
Well, I wrote the script because
- Intel supplies .deb packages so you need to ensure that they have .rpm packages
- I happen to know `dpkg` and `apt` well after 20+ years of use and contribution as a maintainer
- So I know we have a working 'alternatives' mechanism which I use here.

Hence I cannot speak to RHEL/FC.  Good luck though.

**Comment by kkm000** [comment]
@ChukwuemezieChristopherAneke, for the install part, you can look at https://github.com/kaldi-asr/kaldi/blob/master/tools/extras/install_mkl.sh -- we at Kaldi tried our best to handle [as many systems as possible](https://github.com/kkm000/install_mkl) in a user-friendly way. Dunno about the `update-alternatives` counterpart on rhel-based systems, tho, and even if they have it at all.

I vaguely remember they introduced "environments" or something like that; on the very top, abstract level the same idea of isolated packages like virtualenv in Python. So I would be not very surprised if something akin to alternatives exists in rhel and its offshoot distros.

**Comment by eddelbuettel** [comment]
@kkm000 with all due respect this adds zero value.  We can all do a basic `curl` download.  This is all about the subsequent integration.  

Anyway, this repo and its script are very specific about its audience -- it never aimed for anything but `.deb` systems.  So I will lock this now.
