### ISSUE TITLE
when using "sudo", the linux script does not work

### ISSUE THREAD

**Issue by emilBeBri** [eddelbuettel/mkl4deb#4]
in linux, when you  when you get to these commands:

```
echo "/opt/intel/lib/intel64"     >  /etc/ld.so.conf.d/mkl.conf
echo "/opt/intel/mkl/lib/intel64" >> /etc/ld.so.conf.d/mkl.conf
ldconfig
```
you'll get a permission error, if you use "sudo" in order to obtain root permissions in front of each command. This is because sudo only applies to one command at a time.  Either use sudo bash to get a root bash shell, or use quotes around the command with the -sh option, eg.  like this:

sudo sh -c "echo '/usr/local/lib' >> /etc/ld.so.conf"

Perhaps this should be made clear in the otherwise excellent guide?

**Comment by eddelbuettel** [comment]
The idea is to run the entire script at once, ie do

```sh
sudo script.sh
```

Please try that. I am pretty sure that is what I did, and what works.

**Comment by emilBeBri** [comment]
Ah of course :)
