### ISSUE TITLE
Bumping priority number to > 100

### ISSUE THREAD

**Issue by cdluminate** [eddelbuettel/mkl4deb#5]
Sebastien and I bumped Debian's OpenBLAS priority number to 100. That means people who use Buster (or newer) will find this script not working because it assigns 50 to MKL (I guess they still need the `/opt` installation layout for some reason).

**Comment by eddelbuettel** [comment]
Ok, what new default value do you suggest?

**Comment by cdluminate** [comment]
Maybe 120 or 150. Currently OpenBLAS holds three numbers: 100, 95, 90. The priority numbers that will be assigned to BLIS are: 80, 75, 70. Atlas's 35 won't be touched in a short future.

**Comment by eddelbuettel** [comment]
150 sounds good, will do.
