### ISSUE TITLE
Translating into duprkit recipe

### ISSUE THREAD

**Issue by cdluminate** [eddelbuettel/mkl4deb#6]
My experimental toolkit (assume that you have seen my mails on -devel) enables user to manage tricks with dpkg. The trick means something trivial that cannot be uploaded to Debian, but some people will use it to modify the system, e.g. the not-quite-safe apt accelerator:
https://github.com/dupr/duprkit/blob/master/examples/apt-nosync.rcp
mkl4deb is a good example of "trick" as well. Does it sound good if I translate your script into a Recipe as an experiment?

That means, the user can build a `mkl4deb.deb` package (empty). Upon postinst, your script will be executed. Upon prerm, the update-alternative changes will be reverted. In that case this "trick" is managed by dpkg and the user can do less.

**Comment by eddelbuettel** [comment]
Sure, I don't see why not.  We could even turn it into a visible script in the path (maybe `update_mkl` or something) if we write a minimal manual page too.

**Comment by eddelbuettel** [comment]
Upon reflection, it seems that you can simply create a suitable 'duprkit' recipe without me doing anything here.  If that is indeed the case, why don't we close this ticket?
